### PR TITLE
Refined RibbonTrail icon

### PR DESCRIPTION
**Pull request by ghost**
Something like this?

### CODE REVIEW

**Comment by ucupumar** [comment]
That looks pretty neat, but can you make the outline darker like the other icons? Thanks anyway :)

**Comment by ucupumar** [comment]
I'm sorry because of the squashed commits on this branch, this pull request became messed up. Can you do the pull request again, so I can preserve your commit?

**Comment by ucupumar** [comment]
I'm sorry but I just only recently test the icon and I really like it, it's even better than the rest set of icons because it has no black border. I'll let official urho3d-member to decide. I already accepting your commit using cherry-pick, so I close this pull request. Thanks!

**Comment by ghost** [comment]
Doh! Being quite new to branching I didn't realize removing my repository would obviously mess up a pull request.
...let's see if I can do the whole process from memory this time. :)
Glad you like it.

**Comment by ucupumar** [comment]
Don't worry about it now. The pull request and your commit already accepted :)
Thanks for the icon! :+1:

**Comment by ghost** [comment]
Ah, ok. Thanks for the trail. :)
I haven't tried it yet, but will surely try it in the near future.

**Comment by ucupumar** [comment]
You're welcome! :smile:

**Pull request closed without merging**
